name: Run UI Tests For Aviasales page
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5"
jobs:
  run-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
      - name: Cypress.io Chrome
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          headed: true
          record: true
          tag: "aviasales-test-report"
          parallel: true
          group: "UI- Chrome"
          config-file: cypress.config.js
      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: aviasales-test-report
          path: cypress/reports/html/
        if: always()
