name: Run UI Tests For Aviasales page
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"

jobs:
  run-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run tests on chrome
        run: npx cypress run --browser chrome --config video=false
      - name: Generate report
        run: npm run cypress:report
        if: always()
      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: aviasales-test-report
          path: cypress/reports/html/
        if: always()
